_BASE_: "../base-rcnn-fpn.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("cityscapes_val", "cityscapes_foggy_val",)
  BATCH_COMPONENTS: ("labeled_strong", )
EMA:
  ENABLED: False
SOLVER:
  STEPS: (9999,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 2000
OUTPUT_DIR: ""