_BASE_: "./base-rcnn-sim10k.yaml"
MODEL:
  WEIGHTS: "/mnt/hdddata/hotaek/da2od-sim10kbest/cityscapes_cars_val_model_best.pth"
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_train",)
  BATCH_COMPONENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
DA:
  TEACHER:
    ENABLED: True
  DISTILL:
    HARD_ROIH_CLS_ENABLED: False
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: False
    HARD_RPN_REG_ENABLED: False
    ROIH_CLS_ENABLED: True
    OBJ_ENABLED: True
    ROIH_REG_ENABLED: True
    RPN_REG_ENABLED: True
  ALIGN:
    RPN_DA_ENABLED: True
    STYLE_ENABLED: True
    STYLE_ALPHA: 0.3
    STYLE_LEVELS: ["p2", "p3"]
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
SOLVER:
  STEPS: (4999,)
  MAX_ITER: 5000
  BACKWARD_AT_END: False
OUTPUT_DIR: "/mnt/hdddata/hotaek/da2od-sim10kbest/"